In [1]:
import os
import json
import numpy as np
import pandas as pd
from pandas import json_normalize
import matplotlib.pyplot as plt
import seaborn as sns
color = sns.color_palette()
from plotly import tools
import plotly.offline as py
py.init_notebook_mode(connected=True)
import plotly.graph_objs as go

from sklearn import model_selection, preprocessing, metrics

/home/harshit/anaconda3/lib/python3.8/site-packages/pandas/core/computation/expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
#import lightgbm as lgb
pd.options.mode.chained_assignment = None
pd.options.display.max_columns = 999

In [3]:
def load_df(csv_path="/home/harshit/google_analytics/train_v2.csv", nrows=None):
    JSON_COLUMNS = ['device', 'geoNetwork', 'totals', 'trafficSource']
    
    df = pd.read_csv(csv_path, 
                     converters={column: json.loads for column in JSON_COLUMNS}, 
                     dtype={'fullVisitorId': 'str'}, # Important!!
                     nrows=nrows)
    
    for column in JSON_COLUMNS:
        column_as_df = json_normalize(df[column])
        column_as_df.columns = [f"{column}.{subcolumn}" for subcolumn in column_as_df.columns]
        df = df.drop(column, axis=1).merge(column_as_df, right_index=True, left_index=True)
    
    print(f"Loaded {os.path.basename(csv_path)}. Shape: {df.shape}")
    return df

In [4]:
train_df = load_df()

Loaded train_v2.csv. Shape: (1708337, 60)

In [5]:
train_df.shape

(1708337, 60)

In [6]:
train_df.head()

,channelGrouping,customDimensions,date,fullVisitorId,hits,socialEngagementType,visitId,visitNumber,visitStartTime,device.browser,device.browserVersion,device.browserSize,device.operatingSystem,device.operatingSystemVersion,device.isMobile,device.mobileDeviceBranding,device.mobileDeviceModel,device.mobileInputSelector,device.mobileDeviceInfo,device.mobileDeviceMarketingName,device.flashVersion,device.language,device.screenColors,device.screenResolution,device.deviceCategory,geoNetwork.continent,geoNetwork.subContinent,geoNetwork.country,geoNetwork.region,geoNetwork.metro,geoNetwork.city,geoNetwork.cityId,geoNetwork.networkDomain,geoNetwork.latitude,geoNetwork.longitude,geoNetwork.networkLocation,totals.visits,totals.hits,totals.pageviews,totals.bounces,totals.newVisits,totals.sessionQualityDim,totals.timeOnSite,totals.transactions,totals.transactionRevenue,totals.totalTransactionRevenue,trafficSource.campaign,trafficSource.source,trafficSource.medium,trafficSource.keyword,trafficSource.adwordsClickInfo.criteriaParameters,trafficSource.referralPath,trafficSource.isTrueDirect,trafficSource.adContent,trafficSource.adwordsClickInfo.page,trafficSource.adwordsClickInfo.slot,trafficSource.adwordsClickInfo.gclId,trafficSource.adwordsClickInfo.adNetworkType,trafficSource.adwordsClickInfo.isVideoAd,trafficSource.campaignCode
0,Organic Search,"[{'index': '4', 'value': 'EMEA'}]",20171016,3162355547410993243,"[{'hitNumber': '1', 'time': '0', 'hour': '17',...",Not Socially Engaged,1508198450,1,1508198450,Firefox,not available in demo dataset,not available in demo dataset,Windows,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Europe,Western Europe,Germany,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,(not set),not available in demo dataset,not available in demo dataset,not available in demo dataset,1,1,1,1,1,1,NaN,NaN,NaN,NaN,(not set),google,organic,water bottle,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Referral,"[{'index': '4', 'value': 'North America'}]",20171016,8934116514970143966,"[{'hitNumber': '1', 'time': '0', 'hour': '10',...",Not Socially Engaged,1508176307,6,1508176307,Chrome,not available in demo dataset,not available in demo dataset,Chrome OS,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Americas,Northern America,United States,California,San Francisco-Oakland-San Jose CA,Cupertino,not available in demo dataset,(not set),not available in demo dataset,not available in demo dataset,not available in demo dataset,1,2,2,NaN,NaN,2,28,NaN,NaN,NaN,(not set),sites.google.com,referral,NaN,not available in demo dataset,/a/google.com/transportation/mtv-services/bike...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Direct,"[{'index': '4', 'value': 'North America'}]",20171016,7992466427990357681,"[{'hitNumber': '1', 'time': '0', 'hour': '17',...",Not Socially Engaged,1508201613,1,1508201613,Chrome,not available in demo dataset,not available in demo dataset,Android,not available in demo dataset,True,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,mobile,Americas,Northern America,United States,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,windjammercable.net,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,2,2,NaN,1,1,38,NaN,NaN,NaN,(not set),(direct),(none),NaN,not available in demo dataset,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Organic Search,"[{'index': '4', 'value': 'EMEA'}]",20171016,9075655783635761930,"[{'hitNumber': '1', 'time': '0', 'hour': '9', ...",Not Socially Engaged,1508169851,1,1508169851,Chrome,not available in demo dataset,not available in demo dataset,Windows,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Asia,Western Asia,Turkey,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,unknown.unknown,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,2,2,NaN,1,1,1,NaN,NaN,NaN,(not set),google,organic,(not provided),not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Organic Search,"[{'index': '4', 'value': 'Central America'}]",20171016,6960673291025684308,"[{'hitNumber': '1', 'time': '0', 'hour': '14',...",Not Socially Engaged,1508190552,1,1508190552,Chrome,not available in demo dataset,not available in demo dataset,Windows,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Americas,Central America,Mexico,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,prod-infinitum.com.mx,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,2,2,NaN,1,1,52,NaN,NaN,NaN,(not set),google,organic,(not provided),not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
test_df = load_df("/home/harshit/google_analytics/test_v2.csv")

Loaded test_v2.csv. Shape: (401589, 59)

In [8]:
train_df.drop("customDimensions", axis = 1, inplace = True)
test_df.drop("customDimensions", axis = 1, inplace = True)
train_df.drop("hits", axis = 1, inplace = True)
test_df.drop("hits", axis = 1, inplace = True)

In [9]:
train_df

,channelGrouping,date,fullVisitorId,socialEngagementType,visitId,visitNumber,visitStartTime,device.browser,device.browserVersion,device.browserSize,device.operatingSystem,device.operatingSystemVersion,device.isMobile,device.mobileDeviceBranding,device.mobileDeviceModel,device.mobileInputSelector,device.mobileDeviceInfo,device.mobileDeviceMarketingName,device.flashVersion,device.language,device.screenColors,device.screenResolution,device.deviceCategory,geoNetwork.continent,geoNetwork.subContinent,geoNetwork.country,geoNetwork.region,geoNetwork.metro,geoNetwork.city,geoNetwork.cityId,geoNetwork.networkDomain,geoNetwork.latitude,geoNetwork.longitude,geoNetwork.networkLocation,totals.visits,totals.hits,totals.pageviews,totals.bounces,totals.newVisits,totals.sessionQualityDim,totals.timeOnSite,totals.transactions,totals.transactionRevenue,totals.totalTransactionRevenue,trafficSource.campaign,trafficSource.source,trafficSource.medium,trafficSource.keyword,trafficSource.adwordsClickInfo.criteriaParameters,trafficSource.referralPath,trafficSource.isTrueDirect,trafficSource.adContent,trafficSource.adwordsClickInfo.page,trafficSource.adwordsClickInfo.slot,trafficSource.adwordsClickInfo.gclId,trafficSource.adwordsClickInfo.adNetworkType,trafficSource.adwordsClickInfo.isVideoAd,trafficSource.campaignCode
0,Organic Search,20171016,3162355547410993243,Not Socially Engaged,1508198450,1,1508198450,Firefox,not available in demo dataset,not available in demo dataset,Windows,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Europe,Western Europe,Germany,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,(not set),not available in demo dataset,not available in demo dataset,not available in demo dataset,1,1,1,1,1,1,NaN,NaN,NaN,NaN,(not set),google,organic,water bottle,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Referral,20171016,8934116514970143966,Not Socially Engaged,1508176307,6,1508176307,Chrome,not available in demo dataset,not available in demo dataset,Chrome OS,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Americas,Northern America,United States,California,San Francisco-Oakland-San Jose CA,Cupertino,not available in demo dataset,(not set),not available in demo dataset,not available in demo dataset,not available in demo dataset,1,2,2,NaN,NaN,2,28,NaN,NaN,NaN,(not set),sites.google.com,referral,NaN,not available in demo dataset,/a/google.com/transportation/mtv-services/bike...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Direct,20171016,7992466427990357681,Not Socially Engaged,1508201613,1,1508201613,Chrome,not available in demo dataset,not available in demo dataset,Android,not available in demo dataset,True,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,mobile,Americas,Northern America,United States,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,windjammercable.net,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,2,2,NaN,1,1,38,NaN,NaN,NaN,(not set),(direct),(none),NaN,not available in demo dataset,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Organic Search,20171016,9075655783635761930,Not Socially Engaged,1508169851,1,1508169851,Chrome,not available in demo dataset,not available in demo dataset,Windows,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Asia,Western Asia,Turkey,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,unknown.unknown,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,2,2,NaN,1,1,1,NaN,NaN,NaN,(not set),google,organic,(not provided),not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Organic Search,20171016,6960673291025684308,Not Socially Engaged,1508190552,1,1508190552,Chrome,not available in demo dataset,not available in demo dataset,Windows,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Americas,Central America,Mexico,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,prod-infinitum.com.mx,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,2,2,NaN,1,1,52,NaN,NaN,NaN,(not set),google,organic,(not provided),not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1708332,Social,20170104,5123779100307500332,Not Socially Engaged,1483554750,1,1483554750,Chrome,not available in demo dataset,not available in demo dataset,Windows,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Americas,Caribbean,Puerto Rico,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,prtc.net,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,17,15,NaN,1,NaN,626,NaN,NaN,NaN,(not set),youtube.com,referral,NaN,not available in demo dataset,/yt/about/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1708333,Social,20170104,7231728964973959842,Not Socially Engaged,1483543798,1,1483543798,Chrome,not available in demo dataset,not available in demo dataset,Android,not available in demo dataset,True,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,mobile,Asia,Southern Asia,Sri Lanka,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,unknown.unknown,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,18,13,NaN,1,NaN,258,NaN,NaN,NaN,(not set),youtube.com,referral,NaN,not available in demo dataset,/yt/about/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1708334,Social,20170104,5744576632396406899,Not Socially Engaged,1483526434,1,1483526434,Android Webview,not available in demo dataset,not available in demo dataset,Android,not available in demo dataset,True,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,mobile,Asia,Eastern Asia,South Korea,Seoul,(not set),Seoul,not available in demo dataset,unknown.unknown,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,24,21,NaN,1,NaN,991,NaN,NaN,NaN,(not set),youtube.com,referral,NaN,not available in demo dataset,/yt/about/ko/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1708335,Social,20170104,2709355455991750775,Not Socially Engaged,1483592857,1,1483592864,Chrome,not available in demo dataset,not available in demo dataset,Windows,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Asia,Southeast Asia,Indonesia,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,unknown.unknown,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,24,22,NaN,1,NaN,1274,NaN,NaN,NaN,(not set),facebook.com,referral,NaN,not available in demo dataset,/l.php,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1708336,Social,20170104,0814900163617805053,Not Socially Engaged,1483574474,1,1483574474,Chrome,not available in demo dataset,not available in demo dataset,Android,not available in demo dataset,True,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,mobile,Americas,Central America,Mexico,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,cybercable.net.mx,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,31,31,NaN,1,NaN,2653,NaN,NaN,NaN,(not set),youtube.com,referral,NaN,not available in demo dataset,/yt/about/es-419/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
test_df

,channelGrouping,date,fullVisitorId,socialEngagementType,visitId,visitNumber,visitStartTime,device.browser,device.browserVersion,device.browserSize,device.operatingSystem,device.operatingSystemVersion,device.isMobile,device.mobileDeviceBranding,device.mobileDeviceModel,device.mobileInputSelector,device.mobileDeviceInfo,device.mobileDeviceMarketingName,device.flashVersion,device.language,device.screenColors,device.screenResolution,device.deviceCategory,geoNetwork.continent,geoNetwork.subContinent,geoNetwork.country,geoNetwork.region,geoNetwork.metro,geoNetwork.city,geoNetwork.cityId,geoNetwork.networkDomain,geoNetwork.latitude,geoNetwork.longitude,geoNetwork.networkLocation,totals.visits,totals.hits,totals.pageviews,totals.timeOnSite,totals.sessionQualityDim,totals.newVisits,totals.transactions,totals.transactionRevenue,totals.totalTransactionRevenue,totals.bounces,trafficSource.referralPath,trafficSource.campaign,trafficSource.source,trafficSource.medium,trafficSource.keyword,trafficSource.adContent,trafficSource.isTrueDirect,trafficSource.adwordsClickInfo.criteriaParameters,trafficSource.adwordsClickInfo.page,trafficSource.adwordsClickInfo.slot,trafficSource.adwordsClickInfo.gclId,trafficSource.adwordsClickInfo.adNetworkType,trafficSource.adwordsClickInfo.isVideoAd
0,Organic Search,20180511,7460955084541987166,Not Socially Engaged,1526099341,2,1526099341,Chrome,not available in demo dataset,not available in demo dataset,Android,not available in demo dataset,True,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,mobile,Asia,Southern Asia,India,Delhi,(not set),(not set),not available in demo dataset,unknown.unknown,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,4,3,973,1,NaN,NaN,NaN,NaN,NaN,(not set),(not set),google,organic,(not provided),(not set),True,not available in demo dataset,NaN,NaN,NaN,NaN,NaN
1,Direct,20180511,460252456180441002,Not Socially Engaged,1526064483,166,1526064483,Chrome,not available in demo dataset,not available in demo dataset,Macintosh,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Americas,Northern America,United States,California,San Francisco-Oakland-San Jose CA,San Francisco,not available in demo dataset,(not set),not available in demo dataset,not available in demo dataset,not available in demo dataset,1,4,3,49,1,NaN,NaN,NaN,NaN,NaN,(not set),(not set),(direct),(none),(not set),(not set),True,not available in demo dataset,NaN,NaN,NaN,NaN,NaN
2,Organic Search,20180511,3461808543879602873,Not Socially Engaged,1526067157,2,1526067157,Chrome,not available in demo dataset,not available in demo dataset,Chrome OS,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Americas,Northern America,United States,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,onlinecomputerworks.com,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,4,3,24,1,NaN,NaN,NaN,NaN,NaN,(not set),(not set),google,organic,(not provided),(not set),True,not available in demo dataset,NaN,NaN,NaN,NaN,NaN
3,Direct,20180511,975129477712150630,Not Socially Engaged,1526107551,4,1526107551,Chrome,not available in demo dataset,not available in demo dataset,iOS,not available in demo dataset,True,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,mobile,Americas,Northern America,United States,Texas,Houston TX,Houston,not available in demo dataset,(not set),not available in demo dataset,not available in demo dataset,not available in demo dataset,1,5,4,25,1,NaN,NaN,NaN,NaN,NaN,(not set),(not set),(direct),(none),(not set),(not set),True,not available in demo dataset,NaN,NaN,NaN,NaN,NaN
4,Organic Search,20180511,8381672768065729990,Not Socially Engaged,1526060254,1,1526060254,Internet Explorer,not available in demo dataset,not available in demo dataset,Windows,not available in demo dataset,True,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,tablet,Americas,Northern America,United States,California,Los Angeles CA,Irvine,not available in demo dataset,com,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,5,4,49,1,1,NaN,NaN,NaN,NaN,(not set),(not set),google,organic,(not provided),(not set),NaN,not available in demo dataset,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401584,Organic Search,20180907,6701149525099562370,Not Socially Engaged,1536353803,1,1536353803,Chrome,not available in demo dataset,not available in demo dataset,Android,not available in demo dataset,True,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,mobile,Europe,Northern Europe,United Kingdom,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,(not set),not available in demo dataset,not available in demo dataset,not available in demo dataset,1,3,3,111,1,1,NaN,NaN,NaN,NaN,(not set),(not set),google,organic,(not provided),(not set),NaN,not available in demo dataset,NaN,NaN,NaN,NaN,NaN
401585,Organic Search,20180907,6154541330147351453,Not Socially Engaged,1536388075,1,1536388075,Chrome,not available in demo dataset,not available in demo dataset,Windows,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Americas,Northern America,United States,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,(not set),not available in demo dataset,not available in demo dataset,not available in demo dataset,1,3,3,10,1,1,NaN,NaN,NaN,NaN,(not set),(not set),google,organic,(not provided),(not set),NaN,not available in demo dataset,NaN,NaN,NaN,NaN,NaN
401586,Organic Search,20180907,6013469762773705448,Not Socially Engaged,1536351791,3,1536351791,Firefox,not available in demo dataset,not available in demo dataset,Windows,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Europe,Southern Europe,Greece,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,(not set),not available in demo dataset,not available in demo dataset,not available in demo dataset,1,3,3,63,1,NaN,NaN,NaN,NaN,NaN,(not set),(not set),google,organic,(not provided),(not set),True,not available in demo dataset,NaN,NaN,NaN,NaN,NaN
401587,Organic Search,20180907,4565378823441900999,Not Socially Engaged,1536340217,1,1536340217,Chrome,not available in demo dataset,not available in demo dataset,Chrome OS,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Americas,Northern America,United States,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,(not set),not available in demo dataset,not available in demo dataset,not available in demo dataset,1,3,3,64,1,1,NaN,NaN,NaN,NaN,(not set),(not set),google,organic,(not provided),(not set),NaN,not available in demo dataset,NaN,NaN,NaN,NaN,NaN
401588,Direct,20180907,3875690118293601911,Not Socially Engaged,1536331301,1,1536331301,Chrome,not available in demo dataset,not available in demo dataset,Android,not available in demo dataset,True,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,mobile,Asia,Southern Asia,Pakistan,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,worldcall.net.pk,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,3,3,17,1,1,NaN,NaN,NaN,NaN,(not set),(not set),(direct),(none),(not set),(not set),True,not available in demo dataset,NaN,NaN,NaN,NaN,NaN

In [11]:
const_cols = [c for c in train_df.columns if train_df[c].nunique(dropna=False)==1 ]
const_cols

['socialEngagementType',
 'device.browserVersion',
 'device.browserSize',
 'device.operatingSystemVersion',
 'device.mobileDeviceBranding',
 'device.mobileDeviceModel',
 'device.mobileInputSelector',
 'device.mobileDeviceInfo',
 'device.mobileDeviceMarketingName',
 'device.flashVersion',
 'device.language',
 'device.screenColors',
 'device.screenResolution',
 'geoNetwork.cityId',
 'geoNetwork.latitude',
 'geoNetwork.longitude',
 'geoNetwork.networkLocation',
 'totals.visits',
 'trafficSource.adwordsClickInfo.criteriaParameters']

In [12]:
train_df['date']=pd.to_datetime(train_df['date'],format='%Y%m%d').dt.date
test_df['date']=pd.to_datetime(test_df['date'],format='%Y%m%d').dt.date

In [13]:
train_df['date'].max()

datetime.date(2018, 4, 30)

In [14]:
train_df['date'].min()

datetime.date(2016, 8, 1)

In [15]:
print("Variables not in test but in train : ", set(train_df.columns).difference(set(test_df.columns)))

Variables not in test but in train :  {'trafficSource.campaignCode'}

In [16]:
cols_to_drop = const_cols
train_df = train_df.drop(cols_to_drop + ["trafficSource.campaignCode"], axis=1)
test_df = test_df.drop(cols_to_drop, axis=1)

In [17]:
# Impute 0 for missing target values
train_df["totals.transactionRevenue"].fillna(0, inplace=True)
# Impute 0 for missing target values
test_df["totals.transactionRevenue"].fillna(0, inplace=True)

In [18]:
train_y = train_df["totals.transactionRevenue"].copy()

In [19]:
# Unwanted columns
unwanted_columns = ['channelGrouping','trafficSource.campaign','trafficSource.source','trafficSource.medium',
                    'trafficSource.keyword','trafficSource.isTrueDirect','trafficSource.referralPath','trafficSource.adwordsClickInfo.page',
                    'trafficSource.adwordsClickInfo.slot','trafficSource.adwordsClickInfo.gclId','trafficSource.adwordsClickInfo.adNetworkType','trafficSource.adwordsClickInfo.isVideoAd',
                    'trafficSource.adContent' ]

train = train_df.drop(unwanted_columns, axis=1)
test = test_df.drop(unwanted_columns, axis=1)

In [20]:
# # Columns with more than 50% null data
high_null_columns = [c for c in train.columns if train[c].count()<=len(train) * 0.5]
print('Columns more than 50% null values: ', high_null_columns)

Columns more than 50% null values:  ['totals.timeOnSite', 'totals.transactions', 'totals.totalTransactionRevenue']

In [21]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1708337 entries, 0 to 1708336
Data columns (total 25 columns):
 #   Column                          Dtype
---  ------                          -----
 0   date                            object
 1   fullVisitorId                   object
 2   visitId                         int64
 3   visitNumber                     int64
 4   visitStartTime                  int64
 5   device.browser                  object
 6   device.operatingSystem          object
 7   device.isMobile                 bool
 8   device.deviceCategory           object
 9   geoNetwork.continent            object
 10  geoNetwork.subContinent         object
 11  geoNetwork.country              object
 12  geoNetwork.region               object
 13  geoNetwork.metro                object
 14  geoNetwork.city                 object
 15  geoNetwork.networkDomain        object
 16  totals.hits                     object
 17  totals.pageviews                object
 18  totals.bounces                  object
 19  totals.newVisits                object
 20  totals.sessionQualityDim        object
 21  totals.timeOnSite               object
 22  totals.transactions             object
 23  totals.transactionRevenue       object
 24  totals.totalTransactionRevenue  object
dtypes: bool(1), int64(3), object(21)
memory usage: 314.4+ MB

In [22]:
train["totals.totalTransactionRevenue"].fillna(0, inplace=True)
# Impute 0 for missing target values
test["totals.totalTransactionRevenue"].fillna(0, inplace=True)

In [23]:
df = train[["totals.transactions", "totals.transactionRevenue", "totals.totalTransactionRevenue"]]
df

,totals.transactions,totals.transactionRevenue,totals.totalTransactionRevenue
0,NaN,0,0
1,NaN,0,0
2,NaN,0,0
3,NaN,0,0
4,NaN,0,0
...,...,...,...
1708332,NaN,0,0
1708333,NaN,0,0
1708334,NaN,0,0
1708335,NaN,0,0
1708336,NaN,0,0

In [24]:
# Compare the two columns
train.drop('totals.totalTransactionRevenue', axis = 1, inplace = True)
test.drop('totals.totalTransactionRevenue', axis = 1, inplace = True)

In [25]:
train['totals.timeOnSite'].fillna(0, inplace= True)
test['totals.timeOnSite'].fillna(0, inplace= True)
train["totals.transactions"].fillna(0, inplace= True)
test["totals.transactions"].fillna(0, inplace= True)

In [26]:
# # Columns with more than 50% null data
high_null_columns = [c for c in train.columns if train[c].count()<=len(train) * 0.5]
print('Columns more than 50% null values: ', high_null_columns)

Columns more than 50% null values:  []

In [27]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1708337 entries, 0 to 1708336
Data columns (total 24 columns):
 #   Column                     Dtype
---  ------                     -----
 0   date                       object
 1   fullVisitorId              object
 2   visitId                    int64
 3   visitNumber                int64
 4   visitStartTime             int64
 5   device.browser             object
 6   device.operatingSystem     object
 7   device.isMobile            bool
 8   device.deviceCategory      object
 9   geoNetwork.continent       object
 10  geoNetwork.subContinent    object
 11  geoNetwork.country         object
 12  geoNetwork.region          object
 13  geoNetwork.metro           object
 14  geoNetwork.city            object
 15  geoNetwork.networkDomain   object
 16  totals.hits                object
 17  totals.pageviews           object
 18  totals.bounces             object
 19  totals.newVisits           object
 20  totals.sessionQualityDim   object
 21  totals.timeOnSite          object
 22  totals.transactions        object
 23  totals.transactionRevenue  object
dtypes: bool(1), int64(3), object(20)
memory usage: 301.4+ MB

In [28]:
train=train.drop('geoNetwork.continent',axis=1)
# train=train.drop('geoNetwork.country',axis=1)
train=train.drop('geoNetwork.region',axis=1)
train=train.drop('geoNetwork.city',axis=1)
train=train.drop('geoNetwork.networkDomain',axis=1)
test=test.drop('geoNetwork.continent',axis=1)
# test=test.drop('geoNetwork.country',axis=1)
test=test.drop('geoNetwork.region',axis=1)
test=test.drop('geoNetwork.city',axis=1)
test=test.drop('geoNetwork.networkDomain',axis=1)

In [63]:
x = pd.concat([train, test], axis = 0, ignore_index = True)

In [64]:
x.head()

,date,fullVisitorId,visitId,visitNumber,visitStartTime,device.browser,device.operatingSystem,device.isMobile,device.deviceCategory,geoNetwork.subContinent,geoNetwork.country,geoNetwork.metro,totals.hits,totals.pageviews,totals.bounces,totals.newVisits,totals.sessionQualityDim,totals.timeOnSite,totals.transactions,totals.transactionRevenue
0,2017-10-16,3162355547410993243,1508198450,1,1508198450,Firefox,Windows,False,desktop,Western Europe,Germany,not available in demo dataset,1,1,1,1,1,0,0,0
1,2017-10-16,8934116514970143966,1508176307,6,1508176307,Chrome,Chrome OS,False,desktop,Northern America,United States,San Francisco-Oakland-San Jose CA,2,2,NaN,NaN,2,28,0,0
2,2017-10-16,7992466427990357681,1508201613,1,1508201613,Chrome,Android,True,mobile,Northern America,United States,not available in demo dataset,2,2,NaN,1,1,38,0,0
3,2017-10-16,9075655783635761930,1508169851,1,1508169851,Chrome,Windows,False,desktop,Western Asia,Turkey,not available in demo dataset,2,2,NaN,1,1,1,0,0
4,2017-10-16,6960673291025684308,1508190552,1,1508190552,Chrome,Windows,False,desktop,Central America,Mexico,not available in demo dataset,2,2,NaN,1,1,52,0,0

In [68]:
frequency_map_train = x['geoNetwork.country'].value_counts()
x['geoNetwork.country'] = x['geoNetwork.country'].map(frequency_map_train)

In [34]:
x=x.drop('geoNetwork.metro',axis=1)

In [35]:
x['totals.newVisits'].fillna(x['totals.newVisits'].median(),inplace=True)

In [36]:
x.drop('totals.bounces', axis = 1, inplace = True)

In [169]:
data_r = x

In [170]:
data_r

,date,fullVisitorId,visitId,visitNumber,visitStartTime,device.browser,device.operatingSystem,device.isMobile,device.deviceCategory,geoNetwork.subContinent,geoNetwork.country,geoNetwork.metro,totals.hits,totals.pageviews,totals.bounces,totals.newVisits,totals.sessionQualityDim,totals.timeOnSite,totals.transactions,totals.transactionRevenue
0,2017-10-16,3162355547410993243,1508198450,1,1508198450,Firefox,Windows,False,desktop,Western Europe,47988,not available in demo dataset,1,1,1,1,1,0,0,0
1,2017-10-16,8934116514970143966,1508176307,6,1508176307,Chrome,Chrome OS,False,desktop,Northern America,898011,San Francisco-Oakland-San Jose CA,2,2,NaN,NaN,2,28,0,0
2,2017-10-16,7992466427990357681,1508201613,1,1508201613,Chrome,Android,True,mobile,Northern America,898011,not available in demo dataset,2,2,NaN,1,1,38,0,0
3,2017-10-16,9075655783635761930,1508169851,1,1508169851,Chrome,Windows,False,desktop,Western Asia,31618,not available in demo dataset,2,2,NaN,1,1,1,0,0
4,2017-10-16,6960673291025684308,1508190552,1,1508190552,Chrome,Windows,False,desktop,Central America,29869,not available in demo dataset,2,2,NaN,1,1,52,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2109921,2018-09-07,6701149525099562370,1536353803,1,1536353803,Chrome,Android,True,mobile,Northern Europe,91716,not available in demo dataset,3,3,NaN,1,1,111,0,0
2109922,2018-09-07,6154541330147351453,1536388075,1,1536388075,Chrome,Windows,False,desktop,Northern America,898011,not available in demo dataset,3,3,NaN,1,1,10,0,0
2109923,2018-09-07,6013469762773705448,1536351791,3,1536351791,Firefox,Windows,False,desktop,Southern Europe,6924,not available in demo dataset,3,3,NaN,NaN,1,63,0,0
2109924,2018-09-07,4565378823441900999,1536340217,1,1536340217,Chrome,Chrome OS,False,desktop,Northern America,898011,not available in demo dataset,3,3,NaN,1,1,64,0,0
2109925,2018-09-07,3875690118293601911,1536331301,1,1536331301,Chrome,Android,True,mobile,Southern Asia,8457,not available in demo dataset,3,3,NaN,1,1,17,0,0

In [37]:
cat_var = ["device.browser", 'device.operatingSystem', "device.deviceCategory", "geoNetwork.subContinent"]
for j in cat_var:
    fre1 = x[j].value_counts()
    x[j] = x[j].map(fre1)

In [ ]:
x

In [38]:
obj = ['totals.hits', 'totals.pageviews', 'totals.newVisits', 'totals.timeOnSite', 'totals.transactions', 'totals.transactionRevenue']
for i in obj:
    x[i] = x[i].astype("float")

In [ ]:
# Assuming 'train' and 'test' are your DataFrames and 'date' is already a datetime object
# train['date'] = train['date'].apply(lambda x: int(x.strftime('%Y%m%d')))
# test['date'] = test['date'].apply(lambda x: int(x.strftime('%Y%m%d')))

In [39]:
x["device.isMobile"] = x["device.isMobile"].astype("bool")

In [40]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2109926 entries, 0 to 2109925
Data columns (total 18 columns):
 #   Column                     Dtype
---  ------                     -----
 0   date                       object
 1   fullVisitorId              object
 2   visitId                    int64
 3   visitNumber                int64
 4   visitStartTime             int64
 5   device.browser             int64
 6   device.operatingSystem     int64
 7   device.isMobile            bool
 8   device.deviceCategory      int64
 9   geoNetwork.subContinent    int64
 10  geoNetwork.country         int64
 11  totals.hits                float64
 12  totals.pageviews           float64
 13  totals.newVisits           float64
 14  totals.sessionQualityDim   object
 15  totals.timeOnSite          float64
 16  totals.transactions        float64
 17  totals.transactionRevenue  float64
dtypes: bool(1), float64(6), int64(8), object(3)
memory usage: 275.7+ MB

In [41]:
import pandas as pd

# Assuming your DataFrame is named 'df' and the column you're checking is named 'other_column'
x['willpurchase'] = x['totals.transactionRevenue'].apply(lambda x: 1 if x > 0 else 0)

In [42]:
x.drop('visitId',axis=1,inplace=True)
x.drop('totals.sessionQualityDim',axis=1,inplace=True)

In [171]:
df=x.copy()
df['visitDateTime'] = pd.to_datetime(df['visitStartTime'], unit='s', utc=True)
df['visitDateTime'] = df['visitDateTime'].dt.tz_localize(None)  # Correctly removing timezone

# Function to categorize time of day
def categorize_time_of_day(hour):
    if 0 <= hour < 6:
        return 'A'  # Night
    elif 6 <= hour < 12:
        return 'B'  # Morning
    elif 12 <= hour < 18:
        return 'C'  # Afternoon
    else:
        return 'D'  # Evening

# Apply the function to create a new feature
df['timeOfDayCategory'] = df['visitDateTime'].dt.hour.apply(categorize_time_of_day)

print(df[['visitStartTime', 'timeOfDayCategory']])
x=df

         visitStartTime timeOfDayCategory
0            1508198450                 A
1            1508176307                 C
2            1508201613                 A
3            1508169851                 C
4            1508190552                 D
...                 ...               ...
2109921      1536353803                 D
2109922      1536388075                 B
2109923      1536351791                 D
2109924      1536340217                 C
2109925      1536331301                 C

[2109926 rows x 2 columns]

In [44]:
x.drop('visitDateTime',axis=1,inplace=True)
x.drop('visitStartTime',axis=1,inplace=True)

In [45]:
x.drop('fullVisitorId',axis=1,inplace=True)

In [46]:
x.drop('date',axis=1,inplace=True)

In [47]:
x=pd.get_dummies(x)

In [48]:
data_label=x['willpurchase'].copy()
t=['willpurchase','totals.transactionRevenue']
data=x.drop(t,axis=1)

In [49]:
nan_columns = data.isna().any()

In [50]:
data['totals.pageviews']=data['totals.pageviews'][data['totals.pageviews'].median()]

In [ ]:
data.head()

In [51]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,f1_score,precision_score

# Assuming X is your feature matrix and y is your target variable
# Replace X and y with your actual feature matrix and target variable

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(data,data_label, test_size=0.2, random_state=42)

# Create a Random Forest Classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# # Train the classifier on the training data
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [52]:
# # Make predictions on the test data
y_pred = rf_classifier.predict(X_test)

In [53]:
from sklearn.metrics import classification_report,f1_score,precision_score,confusion_matrix
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Confusion Matrix:
 [[417267    142]
 [    61   4516]]

In [54]:
# # Evaluate the performance of the classifier
precision = precision_score(y_test, y_pred)
f1 =f1_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(precision,f1)
# print("Classification Report:\n", classification_rep)

0.9695148132245599 0.9780184082295614

In [55]:
data_r.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2109926 entries, 0 to 2109925
Data columns (total 20 columns):
 #   Column                     Dtype
---  ------                     -----
 0   date                       object
 1   fullVisitorId              object
 2   visitId                    int64
 3   visitNumber                int64
 4   visitStartTime             int64
 5   device.browser             object
 6   device.operatingSystem     object
 7   device.isMobile            bool
 8   device.deviceCategory      object
 9   geoNetwork.subContinent    object
 10  geoNetwork.country         int64
 11  geoNetwork.metro           object
 12  totals.hits                object
 13  totals.pageviews           object
 14  totals.bounces             object
 15  totals.newVisits           object
 16  totals.sessionQualityDim   object
 17  totals.timeOnSite          object
 18  totals.transactions        object
 19  totals.transactionRevenue  object
dtypes: bool(1), int64(4), object(15)
memory usage: 307.9+ MB

In [172]:
df=data_r.copy()
df['visitDateTime'] = pd.to_datetime(df['visitStartTime'], unit='s', utc=True)
df['visitDateTime'] = df['visitDateTime'].dt.tz_localize(None)  # Correctly removing timezone

# Function to categorize time of day
def categorize_time_of_day(hour):
    if 0 <= hour < 6:
        return 'A'  # Night
    elif 6 <= hour < 12:
        return 'B'  # Morning
    elif 12 <= hour < 18:
        return 'C'  # Afternoon
    else:
        return 'D'  # Evening

# Apply the function to create a new feature
df['timeOfDayCategory'] = df['visitDateTime'].dt.hour.apply(categorize_time_of_day)

print(df[['visitStartTime', 'timeOfDayCategory']])
data_r=df

         visitStartTime timeOfDayCategory
0            1508198450                 A
1            1508176307                 C
2            1508201613                 A
3            1508169851                 C
4            1508190552                 D
...                 ...               ...
2109921      1536353803                 D
2109922      1536388075                 B
2109923      1536351791                 D
2109924      1536340217                 C
2109925      1536331301                 C

[2109926 rows x 2 columns]

In [173]:
data_r.drop('visitId', axis = 1, inplace = True)
data_r.drop('fullVisitorId', axis = 1, inplace = True)

In [71]:
data_r.head()

,date,fullVisitorId,visitId,visitNumber,visitStartTime,device.browser,device.operatingSystem,device.isMobile,device.deviceCategory,geoNetwork.subContinent,geoNetwork.country,geoNetwork.metro,totals.hits,totals.pageviews,totals.bounces,totals.newVisits,totals.sessionQualityDim,totals.timeOnSite,totals.transactions,totals.transactionRevenue,visitDateTime,timeOfDayCategory
0,2017-10-16,3162355547410993243,1508198450,1,1508198450,Firefox,Windows,False,desktop,Western Europe,47988,not available in demo dataset,1,1,1,1,1,0,0,0,2017-10-17 00:00:50,A
1,2017-10-16,8934116514970143966,1508176307,6,1508176307,Chrome,Chrome OS,False,desktop,Northern America,898011,San Francisco-Oakland-San Jose CA,2,2,NaN,NaN,2,28,0,0,2017-10-16 17:51:47,C
2,2017-10-16,7992466427990357681,1508201613,1,1508201613,Chrome,Android,True,mobile,Northern America,898011,not available in demo dataset,2,2,NaN,1,1,38,0,0,2017-10-17 00:53:33,A
3,2017-10-16,9075655783635761930,1508169851,1,1508169851,Chrome,Windows,False,desktop,Western Asia,31618,not available in demo dataset,2,2,NaN,1,1,1,0,0,2017-10-16 16:04:11,C
4,2017-10-16,6960673291025684308,1508190552,1,1508190552,Chrome,Windows,False,desktop,Central America,29869,not available in demo dataset,2,2,NaN,1,1,52,0,0,2017-10-16 21:49:12,D

In [174]:

data_r['month']=pd.to_datetime(data_r['date']).dt.month


# Create a function to map months to categories
def categorize_month(month):
    if month in [11, 12, 1]:
        return 'A'
    elif month in [2, 3, 4]:
        return 'B'
    elif month in [5, 6, 7]:
        return 'C'
    elif month in [8, 9, 10]:
        return 'D'

# Apply the function to create the 'category' column
data_r['category'] = data_r['month'].apply(categorize_month)

In [134]:
data_r.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2109926 entries, 0 to 2109925
Data columns (total 22 columns):
 #   Column                     Dtype
---  ------                     -----
 0   date                       object
 1   visitNumber                int64
 2   visitStartTime             int64
 3   device.browser             object
 4   device.operatingSystem     object
 5   device.isMobile            bool
 6   device.deviceCategory      object
 7   geoNetwork.subContinent    object
 8   geoNetwork.country         int64
 9   geoNetwork.metro           object
 10  totals.hits                object
 11  totals.pageviews           object
 12  totals.bounces             object
 13  totals.newVisits           object
 14  totals.sessionQualityDim   object
 15  totals.timeOnSite          object
 16  totals.transactions        object
 17  totals.transactionRevenue  object
 18  visitDateTime              datetime64[ns]
 19  timeOfDayCategory          object
 20  month                      int32
 21  category                   object
dtypes: bool(1), datetime64[ns](1), int32(1), int64(3), object(16)
memory usage: 332.0+ MB

In [175]:
data_r.drop("date", axis = 1, inplace = True)
data_r.drop("visitStartTime", axis = 1, inplace = True)
data_r.drop("month", axis = 1, inplace = True)
data_r.drop("visitDateTime", axis = 1, inplace = True)

In [176]:
obj = ['totals.timeOnSite', 'totals.transactions', 'totals.transactionRevenue']
for i in obj:
    data_r[i] = data_r[i].astype("float")

In [86]:
data_r.isna().sum()
data_r.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2109926 entries, 0 to 2109925
Data columns (total 18 columns):
 #   Column                     Dtype
---  ------                     -----
 0   visitNumber                int64
 1   device.browser             object
 2   device.operatingSystem     object
 3   device.isMobile            bool
 4   device.deviceCategory      object
 5   geoNetwork.subContinent    object
 6   geoNetwork.country         int64
 7   geoNetwork.metro           object
 8   totals.hits                object
 9   totals.pageviews           object
 10  totals.bounces             object
 11  totals.newVisits           object
 12  totals.sessionQualityDim   object
 13  totals.timeOnSite          float64
 14  totals.transactions        float64
 15  totals.transactionRevenue  float64
 16  timeOfDayCategory          object
 17  category                   object
dtypes: bool(1), float64(3), int64(2), object(12)
memory usage: 275.7+ MB

In [177]:
data_r=data_r[data_r['totals.transactionRevenue']>0]

In [90]:
data_r.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23108 entries, 433 to 2108382
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   visitNumber                23108 non-null  int64
 1   device.browser             23108 non-null  object
 2   device.operatingSystem     23108 non-null  object
 3   device.isMobile            23108 non-null  bool
 4   device.deviceCategory      23108 non-null  object
 5   geoNetwork.subContinent    23108 non-null  object
 6   geoNetwork.country         23108 non-null  int64
 7   geoNetwork.metro           23108 non-null  object
 8   totals.hits                23108 non-null  object
 9   totals.pageviews           23108 non-null  object
 10  totals.newVisits           23108 non-null  object
 11  totals.sessionQualityDim   12643 non-null  object
 12  totals.timeOnSite          23108 non-null  float64
 13  totals.transactions        23108 non-null  float64
 14  totals.transactionRevenue  23108 non-null  float64
 15  timeOfDayCategory          23108 non-null  object
 16  category                   23108 non-null  object
dtypes: bool(1), float64(3), int64(2), object(11)
memory usage: 3.0+ MB

In [178]:
data_r.drop("totals.bounces", axis = 1, inplace = True)
data_r["totals.newVisits"].fillna(0, inplace=True)

In [179]:
obj = "totals.sessionQualityDim"
data_r["totals.sessionQualityDim"] = data_r["totals.sessionQualityDim"].astype("float")

In [180]:
data_r["totals.sessionQualityDim"]=data_r["totals.sessionQualityDim"].fillna(data_r["totals.sessionQualityDim"].mean())

In [181]:
data_r['geoNetwork.metro'].value_counts()

geoNetwork.metro
not available in demo dataset               8796
San Francisco-Oakland-San Jose CA           6184
New York NY                                 3004
Chicago IL                                   857
Los Angeles CA                               728
Seattle-Tacoma WA                            629
(not set)                                    560
Austin TX                                    511
Detroit MI                                   324
Boston MA-Manchester NH                      279
Atlanta GA                                   191
Washington DC (Hagerstown MD)                174
Denver CO                                    110
San Diego CA                                  99
Houston TX                                    91
Pittsburgh PA                                 89
Roanoke-Lynchburg VA                          80
London                                        69
Dallas-Ft. Worth TX                           67
Phoenix AZ                                    29
Philadelphia PA                               29
Charlotte NC                                  25
Portland OR                                   21
San Antonio TX                                18
Nashville TN                                  18
Omaha NE                                      14
Miami-Ft. Lauderdale FL                       13
JP_KANTO                                      11
Minneapolis-St. Paul MN                       10
Columbus OH                                    9
Sacramento-Stockton-Modesto CA                 8
Kansas City MO                                 7
Orlando-Daytona Beach-Melbourne FL             7
Raleigh-Durham (Fayetteville) NC               6
Indianapolis IN                                5
Charleston SC                                  5
Fresno-Visalia CA                              3
Baltimore MD                                   3
Las Vegas NV                                   2
Harlingen-Weslaco-Brownsville-McAllen TX       2
Salt Lake City UT                              2
Tampa-St. Petersburg (Sarasota) FL             2
Bluefield-Beckley-Oak Hill WV                  2
Oklahoma City OK                               2
Jacksonville FL                                2
Louisville KY                                  1
Cincinnati OH                                  1
Milwaukee WI                                   1
Hartford & New Haven CT                        1
New Orleans LA                                 1
Syracuse NY                                    1
Chico-Redding CA                               1
Providence-New Bedford,MA                      1
Anchorage AK                                   1
El Paso TX                                     1
Augusta GA                                     1
Name: count, dtype: int64

In [182]:
# Calculate counts of each category
category_counts = data_r['device.browser'].value_counts()

# Identify categories with counts below 100
categories_to_combine = category_counts[category_counts < 100].index.tolist()

# Combine selected categories into 'Other'
data_r['device.browser'] = data_r['device.browser'].apply(lambda x: 'Other' if x in categories_to_combine else x)

In [183]:

# Calculate counts of each category
category_counts = data_r['geoNetwork.subContinent'].value_counts()

# Identify categories with counts below 100
categories_to_combine = category_counts[category_counts < 100].index.tolist()

# Combine selected categories into 'Other'
data_r['geoNetwork.subContinent'] = data_r['geoNetwork.subContinent'].apply(lambda x: 'other_Sub' if x in categories_to_combine else x)

In [184]:
data_r.drop("geoNetwork.country", axis= 1 , inplace = True)

In [185]:
data_r.drop("geoNetwork.metro", axis = 1, inplace = True)

In [186]:
obj = ["totals.hits", "totals.newVisits", "totals.pageviews"]
for i in obj:
    data_r[i] = data_r[i].astype("float")

In [146]:
data_r.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23108 entries, 433 to 2108382
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   visitNumber                23108 non-null  int64
 1   device.browser             23108 non-null  object
 2   device.operatingSystem     23108 non-null  object
 3   device.isMobile            23108 non-null  bool
 4   device.deviceCategory      23108 non-null  object
 5   geoNetwork.subContinent    23108 non-null  object
 6   totals.hits                23108 non-null  float64
 7   totals.pageviews           23108 non-null  float64
 8   totals.newVisits           23108 non-null  float64
 9   totals.sessionQualityDim   23108 non-null  float64
 10  totals.timeOnSite          23108 non-null  float64
 11  totals.transactions        23108 non-null  float64
 12  totals.transactionRevenue  23108 non-null  float64
 13  timeOfDayCategory          23108 non-null  object
 14  category                   23108 non-null  object
dtypes: bool(1), float64(7), int64(1), object(6)
memory usage: 2.7+ MB

In [187]:
import lightgbm as lgb

In [188]:
data_r = pd.get_dummies(data_r)

In [189]:
data_r.drop("device.operatingSystem_Windows Phone", axis = 1, inplace = True)

In [190]:
data_r.head()

,visitNumber,device.isMobile,totals.hits,totals.pageviews,totals.newVisits,totals.sessionQualityDim,totals.timeOnSite,totals.transactions,totals.transactionRevenue,device.browser_Chrome,device.browser_Firefox,device.browser_Internet Explorer,device.browser_Other,device.browser_Safari,device.operatingSystem_Android,device.operatingSystem_Chrome OS,device.operatingSystem_Linux,device.operatingSystem_Macintosh,device.operatingSystem_Windows,device.operatingSystem_iOS,device.deviceCategory_desktop,device.deviceCategory_mobile,device.deviceCategory_tablet,geoNetwork.subContinent_Eastern Asia,geoNetwork.subContinent_Northern America,geoNetwork.subContinent_Northern Europe,geoNetwork.subContinent_South America,geoNetwork.subContinent_other_Sub,timeOfDayCategory_A,timeOfDayCategory_B,timeOfDayCategory_C,timeOfDayCategory_D,category_A,category_B,category_C,category_D
433,4,False,9.0,9.0,0.0,13.0,261.0,1.0,15190000.0,True,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,False,False,True,False,False,False,False,False,False,True
550,11,False,15.0,12.0,0.0,38.0,285.0,1.0,8000000.0,True,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False,False,False,False,False,False,True,False,False,False,True
555,6,True,15.0,15.0,0.0,42.0,1044.0,1.0,57300000.0,False,False,False,False,True,False,False,False,False,False,True,False,True,False,False,True,False,False,False,False,False,True,False,False,False,False,True
597,17,False,18.0,16.0,0.0,77.0,514.0,1.0,18230000.0,True,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,False,False,False,False,False,True,False,False,False,True
619,1,False,21.0,20.0,1.0,62.0,487.0,1.0,12310000.0,True,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,False,False,False,False,False,True,False,False,False,True

In [191]:
x=data_r

In [193]:
x.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23108 entries, 433 to 2108382
Data columns (total 36 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   visitNumber                               23108 non-null  int64
 1   device.isMobile                           23108 non-null  bool
 2   totals.hits                               23108 non-null  float64
 3   totals.pageviews                          23108 non-null  float64
 4   totals.newVisits                          23108 non-null  float64
 5   totals.sessionQualityDim                  23108 non-null  float64
 6   totals.timeOnSite                         23108 non-null  float64
 7   totals.transactions                       23108 non-null  float64
 8   totals.transactionRevenue                 23108 non-null  float64
 9   device.browser_Chrome                     23108 non-null  bool
 10  device.browser_Firefox                    23108 non-null  bool
 11  device.browser_Internet Explorer          23108 non-null  bool
 12  device.browser_Other                      23108 non-null  bool
 13  device.browser_Safari                     23108 non-null  bool
 14  device.operatingSystem_Android            23108 non-null  bool
 15  device.operatingSystem_Chrome OS          23108 non-null  bool
 16  device.operatingSystem_Linux              23108 non-null  bool
 17  device.operatingSystem_Macintosh          23108 non-null  bool
 18  device.operatingSystem_Windows            23108 non-null  bool
 19  device.operatingSystem_iOS                23108 non-null  bool
 20  device.deviceCategory_desktop             23108 non-null  bool
 21  device.deviceCategory_mobile              23108 non-null  bool
 22  device.deviceCategory_tablet              23108 non-null  bool
 23  geoNetwork.subContinent_Eastern Asia      23108 non-null  bool
 24  geoNetwork.subContinent_Northern America  23108 non-null  bool
 25  geoNetwork.subContinent_Northern Europe   23108 non-null  bool
 26  geoNetwork.subContinent_South America     23108 non-null  bool
 27  geoNetwork.subContinent_other_Sub         23108 non-null  bool
 28  timeOfDayCategory_A                       23108 non-null  bool
 29  timeOfDayCategory_B                       23108 non-null  bool
 30  timeOfDayCategory_C                       23108 non-null  bool
 31  timeOfDayCategory_D                       23108 non-null  bool
 32  category_A                                23108 non-null  bool
 33  category_B                                23108 non-null  bool
 34  category_C                                23108 non-null  bool
 35  category_D                                23108 non-null  bool
dtypes: bool(28), float64(7), int64(1)
memory usage: 2.2 MB

In [197]:
# Columns to process
cols_to_process = ["visitNumber", "totals.hits", "totals.pageviews", "totals.sessionQualityDim", "totals.timeOnSite", "totals.transactions",'totals.transactionRevenue']
df=x
# Convert columns to numeric and handle missing values
for col in cols_to_process:
    df[col] = pd.to_numeric(df[col], errors='coerce')  # Coerce any non-numeric values to NaN
    df[col].fillna(df[col].median(), inplace=True)    # Replace NaNs with median

# Calculate Q1, Q3, and IQR for the specified columns
Q1 = df[cols_to_process].quantile(0.25)
Q3 = df[cols_to_process].quantile(0.75)
IQR = Q3 - Q1

# Calculate lower and upper bounds for the specified columns
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Replace outliers with column median
for col in cols_to_process:
    df[col] = df[col].mask((df[col] < lower_bound[col]) | (df[col] > upper_bound[col]), df[col].median())

In [199]:
# df

In [200]:
df_label = data_r["totals.transactionRevenue"].copy()
df.drop("totals.transactionRevenue", axis = 1, inplace = True)

In [159]:
train1=df
train1_y=df_label

In [201]:
import re
from sklearn.model_selection import KFold
from sklearn.metrics import mean_absolute_error, r2_score
import numpy as np
# Clean feature names
train1.columns = [re.sub('[^a-zA-Z0-9_]', '', col) for col in train1.columns]
# Load the data
X =train1  # Your training data features
y =train1_y# Your target variable

# # Take the logarithm of the target variable
y_log = np.log1p(y)

# Create a LightGBM dataset
train_data = lgb.Dataset(X, label=y_log)

# Specify the parameters for the LightGBM model
params = {
    'objective': 'regression',
    'metric': 'rmse',
    'num_leaves': 31,
    'learning_rate': 0.1,
    'n_estimators': 1000,
}

# Perform K-fold cross-validation without early stopping
cv = KFold(n_splits=5, shuffle=True)

for fold, (train_index, val_index) in enumerate(cv.split(X, y_log)):
    X_train, X_val = X.iloc[train_index], X.iloc[val_index]
    y_train, y_val = y_log.iloc[train_index], y_log.iloc[val_index]

    train_set = lgb.Dataset(X_train, label=y_train)
    val_set = lgb.Dataset(X_val, label=y_val)

    # Initialize the model without early stopping
    model = lgb.train(params, train_set, num_boost_round=1000)

    # Evaluate the model on the validation set
    preds_log = model.predict(X_val)
    rmse = mean_absolute_error(y_val, preds_log)
    r2 = r2_score(y_val, preds_log)

    # Convert predictions back to the original scale
    preds = np.expm1(preds_log)

    print('Fold {} RMSE: {:.4f}, R2 Score: {:.4f}'.format(fold + 1, rmse, r2))

/home/harshit/anaconda3/lib/python3.8/site-packages/lightgbm/engine.py:172: UserWarning:

Found `n_estimators` in params. Will use it instead of argument

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003298 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 494
[LightGBM] [Info] Number of data points in the train set: 18486, number of used features: 34
[LightGBM] [Info] Start training from score 2.930264
Fold 1 RMSE: 0.0445, R2 Score: 0.0972
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002029 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 494
[LightGBM] [Info] Number of data points in the train set: 18486, number of used features: 34
[LightGBM] [Info] Start training from score 2.930722

/home/harshit/anaconda3/lib/python3.8/site-packages/lightgbm/engine.py:172: UserWarning:

Found `n_estimators` in params. Will use it instead of argument

Fold 2 RMSE: 0.0445, R2 Score: 0.1238
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001766 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 494
[LightGBM] [Info] Number of data points in the train set: 18486, number of used features: 34
[LightGBM] [Info] Start training from score 2.930568

/home/harshit/anaconda3/lib/python3.8/site-packages/lightgbm/engine.py:172: UserWarning:

Found `n_estimators` in params. Will use it instead of argument

Fold 3 RMSE: 0.0454, R2 Score: 0.1023
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002067 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 494
[LightGBM] [Info] Number of data points in the train set: 18487, number of used features: 34
[LightGBM] [Info] Start training from score 2.930575

/home/harshit/anaconda3/lib/python3.8/site-packages/lightgbm/engine.py:172: UserWarning:

Found `n_estimators` in params. Will use it instead of argument

Fold 4 RMSE: 0.0451, R2 Score: 0.1056
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001705 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 494
[LightGBM] [Info] Number of data points in the train set: 18487, number of used features: 34
[LightGBM] [Info] Start training from score 2.930314

/home/harshit/anaconda3/lib/python3.8/site-packages/lightgbm/engine.py:172: UserWarning:

Found `n_estimators` in params. Will use it instead of argument

Fold 5 RMSE: 0.0450, R2 Score: 0.1055

In [161]:
train1_y = np.log1p(train1_y)

In [164]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error, r2_score

# Assuming X is your feature matrix and y is your target variable
# Replace X and y with your actual feature matrix and target variable

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(train1,train1_y, test_size=0.2, random_state=42)

# Create a Random Forest Classifier
xgb_model = xgb.XGBRegressor(objective = "reg:squarederror", seed = 42)

# # Train the classifier on the training data
xgb_model.fit(X_train, y_train)

y_reg_pred = xgb_model.predict(X_test)

mse = mean_squared_error(y_test, y_reg_pred)

r2_reg = r2_score(y_test, y_reg_pred)
print(mse, r2_reg)

1.1924378840340308 0.14446912700426973

In [ ]:
y_reg_pred1 = xgb_model.predict(X_train)


mse = mean_squared_error(y_reg_pred1 , y_train)

r2_reg = r2_score(y_test, y_reg_pred)
print(mse, r2_reg)

In [ ]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

# Your data processing steps...

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(data_reg, data_reg_label, test_size=0.2, random_state=42)

# Create an XGBoost Regressor with some hyperparameters (these are just placeholders)
xgb_model = xgb.XGBRegressor(
    objective="reg:squarederror", 
    seed=42, 
    n_estimators=100, 
    max_depth=30, 
    learning_rate=0.001
)

# Train the model on the training data
xgb_model.fit(X_train, y_train)

# Predict on the test data
y_reg_pred = xgb_model.predict(X_train)

# Calculate metrics
mse = mean_squared_error(y_train, y_reg_pred)
r2_reg = r2_score(y_train, y_reg_pred)

print("MSE:", mse, "R2:", r2_reg)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Assuming 'data_reg' is your feature matrix and 'data_reg_label' is your target variable

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(data_reg, data_reg_label, test_size=0.2, random_state=42)

# Create a Random Forest Regressor
rf_regressor = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the regressor on the training data
rf_regressor.fit(X_train, y_train)

# Predict on the test data
y_pred = rf_regressor.predict(X_test)

# Calculate MSE and R2 Score
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R2 Score:", r2)

In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'max_depth': [10, 12, 15],
    'n_estimators': [50, 100, 200]
}

# Perform GridSearchCV for hyperparameter tuning
grid_search = GridSearchCV(rf_regressor, param_grid, cv=3, scoring='r2')
grid_search.fit(X_train, y_train)

# Get the best model from the grid search
best_model = grid_search.best_estimator_

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate R-squared
r2 = r2_score(y_test, y_pred)
print(f'R-squared: {r2}')